{
  imports = [
    <plasma-manager/modules>
    # generated by `nix run github:pjones/plasma-manager > plasma-gen.nix`
    ./plasma-gen.nix
  ];
  programs.plasma = {
    enable = true;
  };
  home.file.".config/plasma-workspace/env/env.sh" = {
    # When a new terminal window is launched by Plasma, it doesn't respect the
    # home-manager configured socket for TMUX. So force it here.
    text = ''
      #!/usr/bin/env sh
      export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
    '';
    executable = true;
  };
}
