{ plasma-manager, lib, ... }:

{
  imports = [
    plasma-manager.homeManagerModules.plasma-manager
    # generated by `nix run github:pjones/plasma-manager > plasma-gen.nix`
    ./plasma-gen.nix
  ];
  programs.plasma = {
    enable = true;
  };
  
  # Set TMUX temporary directory via session variables instead of script
  # Use mkDefault to allow tmux module to override if needed
  home.sessionVariables = {
    TMUX_TMPDIR = lib.mkDefault "$XDG_RUNTIME_DIR";
  };
}
